name: redoc

on:
  #release:
    #types: [published]
  # temp for testing
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: Tag/version to publish

jobs:
  redoc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version
        shell: bash
        run: echo "::set-output name=tag::sha-$(git rev-parse --short HEAD | sed s/^v//g)"
        id: version

      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle api/swagger.yml -o docs/reference/api.html'

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_API_REFERENCE }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
            SOURCE_DIR: 'docs/reference/api.html'
            DEST_DIR: 'index.html'

